version: '4'

services:
  app:
    build: .
    command: node index.js
    ports: 
      - 3002:3002
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    build: /db-conf
    environment:
      - POSTGRES_PASSWORD=P0stgrePass
      - POSTGRES_DB=rentdb
    ports:
      - 5432:5432
